service: softek-serverless

useDotenv: true

plugins:
  - serverless-offline
  # - serverless-dotenv-plugin

build:
  esbuild:
    # Path to the esbuild config file relative to the `serverless.yml` file
    # configFile: ./esbuild.config.mjs
    # Enable or Disable bundling the function code and dependencies. (Default: true)
    bundle: true
    # Enable minifying function code. (Default: false)
    minify: true
    # NPM packages to not be bundled. Glob patterns are supported here.
    # external:
    #   - 'class-transformer'
    #   - '@nestjs/config'
    #   - '@nestjs/microservices'
    #   - '@nestjs/websockets'
    # NPM packages to not be bundled, as well as not included in node_modules
    # in the zip file uploaded to Lambda. By default this will be set to aws-sdk
    # if the runtime is set to nodejs16.x or lower or set to @aws-sdk/* if set to nodejs18.x or higher.
    # Glob patterns are supported here.
    # exclude:
    #   - '@aws-sdk/*'
      # - '!@aws-sdk/client-bedrock-runtime'
    # The packages config, this can be set to override the behavior of external
    # If this is set then all dependencies will be treated as external and not bundled.
    packages: external
    # By default Framework will attempt to build and package all functions concurrently.
    # This property can bet set to a different number if you wish to limit the
    # concurrency of those operations.
    # buildConcurrency: 3
    # Enable or configure sourcemaps, can be set to true or to an object with further configuration.
    # sourcemap:
    #   # The sourcemap type to use, options are (inline, linked, or external)
    #   type: linked
    #   # Whether to set the NODE_OPTIONS on functions to enable sourcemaps on Lambda
    #   setNodeOptions: true

package:
  individually: true
  exclude:
    - ../../node_modules/**
    - ./src/**
    - ./test/**
    - .serverless/**
    - .serverless_plugins/**
  include:
    - .env
#     - '../../node_modules/@nestjs/common/**'
#     - '../../node_modules/@nestjs/core/**'
#     - '../../node_modules/@nestjs/schematics/**'
#     - '../../node_modules/@nestjs/testing/**'
#     - '../node_modules/@nestjs/config/**'
#     - '../../node_modules/tslib/**'
#     - '../../node_modules/reflect-metadata/**'
#     - '../../node_modules/uid/**'
#     - '../../node_modules/rxjs/**'
#     - '../../node_modules/iterare/**'
#     - '../../node_modules/@nuxtjs/**'
#     - '../../node_modules/fast-safe-stringify/**'
#     - '../../node_modules/path-to-regexp/**'
#     - '../../node_modules/cache-manager/**'
#     - '../../node_modules/class-transformer/**'
#     - '../../node_modules/class-validator/**'
#     - '../../node_modules/cache-manager/**'
#     - '../../node_modules/@angular-devkit/**'
#     - '../../node_modules/jsonc-parser/**'
#     - '../../node_modules/pluralize/**'
#     - '../../node_modules/body-parser/**'
#     - '../../node_modules/cors/**'
#     - '../../node_modules/express/**'
#     - '../../node_modules/multer/**'
#     - '../../node_modules/@vendia/**'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 1024
  timeout: 29
  stage: 'dev'
  environment:
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USER: ${DATABASE_USER}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}


functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

